### ISSUE TITLE
Build failure not caught by Fastlane

### ISSUE THREAD

**Issue by galalmounir** [safu9/fastlane-plugin-unity#3]
When a unity build fails, Fastlane still assumes that the build has succeeded

**Comment by safu9** [comment]
To stop fastlane, you need to throw exception in your build script,
or call EditorApplication.Exit with a non-zero return code.
Please see the docs of executeMethod option at: https://docs.unity3d.com/Manual/CommandLineArguments.html

**Comment by safu9** [comment]
Note that this plugin is for launching unity in command line from fastlane, and the rest of the work, such as building your app, is entirely up to you.
